### ISSUE TITLE
Piper container no working working?

### ISSUE THREAD

**Issue by ignacio82** [rhasspy/wyoming-piper#10]
I woke up to piper no longer and I was hoping someone could point me in the right direction to fix this. 

This is what my log shows:

```
    TtsVoice(
TypeError: __init__() missing 1 required positional argument: 'version'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 209, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 88, in main
    voices = [
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 89, in <listcomp>
    TtsVoice(
TypeError: __init__() missing 1 required positional argument: 'version'
```

![image](https://github.com/rhasspy/wyoming-piper/assets/1833309/a42284b3-b08e-4934-89e8-7a2f6afb14fa)

And this is my docker-compose:

```
##
  piper:
    container_name: Piper
    image: rhasspy/wyoming-piper
    user: 1026:100
    ports:
      - '10200:10200'
    volumes:
      - nfs-piper:/data
      - nfs-wyoming_piper:/usr/local/lib/python3.9/dist-packages/wyoming_piper
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    command: --voice en-us-ryan-low
    restart: unless-stopped
```

**Comment by synesthesiam** [comment]
Please try version 2.0
