### ISSUE TITLE
Are only official voice models allowed for Home Assistant?

### ISSUE THREAD

**Issue by ei23fxg** [rhasspy/wyoming-piper#6]
While it is possible to use a custom onnx models with commands and the API, when copied into the data folder, it is not possible to use them in Home Assistant docker with the voice assistant tool or play tts over media player.
They are visible, but they can't be used that way:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-31' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:28> exception=VoiceNotFoundError('testvoice')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 35, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/handler.py", line 73, in handle_event
    piper_proc = await self.process_manager.get_process(voice_name=voice_name)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/process.py", line 114, in get_process
    ensure_voice_exists(
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 77, in ensure_voice_exists
    find_voice(name, data_dirs)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 183, in find_voice
    raise VoiceNotFoundError(name)
wyoming_piper.download.VoiceNotFoundError: testvoice
```

Are there only official voice models allowed?

Maybe in download.py is a hint:
```
    if name not in voices_info:
        # Try as name or file path to a custom voice.
        #
        # This will raise VoiceNotFoundError if the onnx model or config file
        # can't be found.
        find_voice(name, data_dirs)
        return
```
But i don't quite get it...

**Comment by ei23fxg** [comment]
I'm stupid!
I got it working.
If your files are for example:
`de_DE-testvoice-high.onnx`
`de_DE-testvoice-high.onnx.json`

Just don't set
`    "dataset": "testvoice"`
just take the full filename like so
`    "dataset": "de_DE-testvoice-high"`
and it works!

Thank you anyway for the great work!
